### ISSUE TITLE
Add linter on github actions

### ISSUE THREAD

**Issue by JohnAndante** [JohnAndante/nospheratus-must-die#4]
## Description

Necessary to add a linter to trigger on commits or pushs.

Found this example on anoter project:

```yaml
name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint GDScript
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install gdtoolkit
        run: |
          python -m pip install --upgrade pip
          python -m pip install 'gdtoolkit==4.*'

      - name: Lint GDScript files
        run: |
          gdlint --verbose scripts/ scenes/ addons/ || true
          gdlint scripts/ scenes/ addons/

      - name: Format check GDScript files
        run: |
          gdformat --check scripts/ scenes/ addons/
```
